name: holyhabit
description: A workout + RPG Flutter app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 네트워크
  dio: ^5.4.0

  # 상태관리
  provider: ^6.1.1

  # 보안 저장소
  flutter_secure_storage: ^9.0.0

  # Google 로그인
  google_sign_in: ^6.2.1

  # 라우팅
  go_router: ^13.0.0

  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0

  #만보기
  pedometer: ^4.1.1
  shared_preferences: ^2.2.2

  #svg
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/space/space_bg.png
    - assets/images/adventure/
    - assets/images/characters/knight/
    - assets/images/characters/holy/
    - assets/images/monsters/monster1/
    - assets/images/characters/dragon/
    - assets/images/space/
    - assets/images/ui/
    - assets/images/ui/island/
    - assets/images/ui/select_ui.svg
    - assets/images/ui/Characte_background/
    - assets/images/ui/Characte_slot/
    - assets/images/space/planet1/
    - assets/images/ui/home_background/
    - assets/images/onboarding/
    - assets/images/onboarding/icon/
    - assets/images/ui/icon/
    - assets/images/shop/

  uses-material-design: true

  fonts:
    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/fonts/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Paperlogy-9Black.ttf
          weight: 900
    - family: Waguri
      fonts:
        - asset: assets/fonts/WAGURI TTF.ttf